# Generated by Django 2.2.10 on 2021-02-15 16:26

from django.db import migrations, models
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/courses')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', django_countries.fields.CountryField(default='', max_length=2)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
